
version: '4.2'

services:
  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - app-network

  # API Gateway service
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - reservation-service
      - payment-service
    environment:
      - RESERVATION_SERVICE_URL=http://reservation-service:3001
      - PAYMENT_SERVICE_URL=http://payment-service:3002
    networks:
      - app-network

  # Reservation microservice
  reservation-service:
    build: ./microservice-reservation/backend
    ports:
      - "3001:3001"
    depends_on:
      - reservation-db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@reservation-db:5432/reservation_db
    networks:
      - app-network

  # Reservation database
  reservation-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reservation_db
    volumes:
      - reservation-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Payment microservice
  payment-service:
    build: ./microservice-paiement/backend
    ports:
      - "3002:3002"
    depends_on:
      - payment-db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@payment-db:5432/payment_db
    networks:
      - app-network

  # Payment database
  payment-db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_db
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  reservation-db-data:
  payment-db-data:
