# ========== CANARY DEPLOYMENT ==========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-canary
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      track: canary
  template:
    metadata:
      labels:
        app: frontend
        track: canary
    spec:
      containers:
      - name: frontend
        image: mbrabaa2023/front_end:2ac04ae83b674c329779b10cacbbfa26b7d777a0
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
# ========== CANARY SERVICE ==========
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary-service
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: frontend
    track: canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30083