apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  revisionHistoryLimit: 3  # Limite le nombre de revisions conservées
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: $DOCKER_IMAGE:$TAG
        imagePullPolicy: IfNotPresent  # Changé pour optimiser les pulls
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http  # Référence au port nommé
            scheme: HTTP
          initialDelaySeconds: 30  # Délai réduit mais suffisant
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 5  # Délai plus court pour readiness
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:  # Ajout d'une startupProbe
          httpGet:
            path: /
            port: http
            scheme: HTTP
          failureThreshold: 30  # Nombre élevé pour les apps qui démarrent lentement
          periodSeconds: 10