apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: NodePort  # Changé de LoadBalancer à NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80      # Port interne du service
      targetPort: 80  # Port du container
      nodePort: 30080  # Port optionnel (30000-32767)