apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-alerts
  namespace: monitoring
spec:
  groups:
  - name: cluster-health
    rules:
    - alert: NodeDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
        service: infrastructure
      annotations:
        summary: "Node {{ $labels.instance }} is down"
        description: "Le noeud {{ $labels.instance }} ne répond pas depuis 1 minute"

    - alert: HighMemoryUsage
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
      for: 5m
      labels:
        severity: warning
        service: infrastructure
      annotations:
        summary: "High memory usage on {{ $labels.instance }}"
        description: "Utilisation mémoire à {{ $value | printf \"%.2f\" }}% depuis 5 minutes"

    - alert: HighCPUUsage
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100 > 80
      for: 5m
      labels:
        severity: warning
        service: infrastructure
      annotations:
        summary: "High CPU usage on {{ $labels.instance }}"
        description: "Utilisation CPU à {{ $value | printf \"%.2f\" }}% depuis 5 minutes"