global:
  smtp_from: "${{ secrets.SMTP_USER }}"
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: "${{ secrets.SMTP_USER }}"
  smtp_auth_password: "${{ secrets.SMTP_PASSWORD }}"
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: "${{ secrets.ALERT_EMAIL }}"
    send_resolved: true