apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-alerts
  namespace: monitoring
  labels:
    release: monitoring
    app: kube-prometheus-stack
spec:
  groups:
  - name: cluster-alerts
    rules:
    - alert: HighMemoryUsage
      expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High memory usage on {{ $labels.instance }}"
        description: "Memory available is less than 10% on {{ $labels.instance }}"
    - alert: HighCPUUsage
      expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100 > 70
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on {{ $labels.instance }}"
        description: "CPU usage is over 70% for 10 minutes on {{ $labels.instance }}"
    - alert: PodNotRunning
      expr: kube_pod_status_phase{phase!="Running",namespace="frontend"} > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod not running in frontend namespace ({{ $labels.pod }})"
        description: "Pod {{ $labels.pod }} in namespace frontend has been not Running for more than 5 minutes (current status: {{ $labels.phase }})"