alertmanager:
  enabled: false  # Désactivé car déployé séparément

prometheus:
  service:
    type: NodePort
    nodePort: 30090  # Port pour l'UI Prometheus
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    ruleSelector:
      matchLabels:
        release: monitoring
        app: kube-prometheus-stack
    ruleNamespaceSelector:
      matchLabels:
        name: monitoring
    alertmanagers:
    - static_configs:
      - targets: ['alertmanager.monitoring.svc:9093']  # Cible le Service ClusterIP
      scheme: http
      pathPrefix: /
      timeout: 10s

grafana:
  adminUser: "${{ secrets.GRAFANA_ADMIN_USER }}"
  adminPassword: "${{ secrets.GRAFANA_ADMIN_PASSWORD }}"
  service:
    type: NodePort
    nodePort: 30091  # Port pour l'UI Grafana

prometheus-node-exporter:
  hostRootFsMount: false 