alertmanager:
  enabled: false  

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: web

grafana:
  adminUser: "${{ secrets.GRAFANA_ADMIN_USER }}"
  adminPassword: "${{ secrets.GRAFANA_ADMIN_PASSWORD }}"
